-- Codigo ejecutado por usuario admin de la base de datos:

-- CREACION DE USUARIO CONEXION PARA APLICACION
-- Crear el usuario del sistema
CREATE USER reef_user IDENTIFIED BY ReefReserve2024
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

-- Otorgar privilegios al usuario del sistema
GRANT CONNECT, RESOURCE TO reef_user;

-- Codigo ejecutado por usuario reef_user dueño de tablas:

-- Eliminar las tablas en orden

DROP TABLE reserva CASCADE CONSTRAINTS;
DROP TABLE fotografia CASCADE CONSTRAINTS;
DROP TABLE habitacion CASCADE CONSTRAINTS;
DROP TABLE usuario CASCADE CONSTRAINTS;
DROP TABLE tipo_usuario CASCADE CONSTRAINTS;
DROP TABLE categoria_hab CASCADE CONSTRAINTS;
DROP TABLE estado_hab CASCADE CONSTRAINTS;
DROP TABLE estado_reserva CASCADE CONSTRAINTS;
DROP TABLE ubicacion CASCADE CONSTRAINTS;

-- CREACION DE TABLAS DE APLICACION
CREATE TABLE categoria_hab (
    id_categoria NUMBER GENERATED BY DEFAULT AS IDENTITY,
    desc_cat     VARCHAR2(100) NOT NULL
);

CREATE TABLE estado_hab (
    id_estado  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    desc_est_hab VARCHAR2(100) NOT NULL
);

CREATE TABLE estado_reserva (
    id_estado    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    desc_est_res VARCHAR2(100) NOT NULL
);

CREATE TABLE fotografia (
    id_fotografia  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    url_fotografia VARCHAR2(255) NOT NULL,
    id_habitacion  NUMBER NOT NULL
);

CREATE TABLE habitacion (
    id_habitacion    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    numero_hab       VARCHAR2(50) NOT NULL,
    info_hab         VARCHAR2(255),
    equipamiento_hab VARCHAR2(255),
    valor_diario_hab NUMBER NOT NULL,
    id_ubicacion     NUMBER NOT NULL,
    id_estado        NUMBER NOT NULL,
    id_categoria     NUMBER NOT NULL
);

CREATE TABLE reserva (
    id_reserva    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    fecha_inicio  DATE NOT NULL,
    fecha_termino DATE NOT NULL,
    cantidad_dias NUMBER NOT NULL,
    abono         NUMBER,
    costo         NUMBER NOT NULL,
    id_usuario    NUMBER NOT NULL,
    id_habitacion NUMBER NOT NULL,
    id_estado     NUMBER NOT NULL
);

CREATE TABLE tipo_usuario (
    id_tipo_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY,
    descripcion     VARCHAR2(100) NOT NULL
);

CREATE TABLE ubicacion (
    id_ubicacion NUMBER GENERATED BY DEFAULT AS IDENTITY,
    desc_ubic    VARCHAR2(100) NOT NULL
);

CREATE TABLE usuario (
    id_usuario         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    correo_electronico VARCHAR2(150) NOT NULL,
    clave_usuario      VARCHAR2(100) NOT NULL,
    nombre_usuario     VARCHAR2(100) NOT NULL,
    apellido_usuario   VARCHAR2(100) NOT NULL,
    id_tipo_usuario    NUMBER NOT NULL
);

-- CREACION DE CONSTRAINTS Y PK (PRIMARY KEY)

ALTER TABLE categoria_hab ADD CONSTRAINT pk_categoria_hab PRIMARY KEY ( id_categoria );

ALTER TABLE estado_hab ADD CONSTRAINT pk_estado_hab PRIMARY KEY ( id_estado );

ALTER TABLE estado_reserva ADD CONSTRAINT pk_estado_reserva PRIMARY KEY ( id_estado );

ALTER TABLE fotografia ADD CONSTRAINT pk_fotografia PRIMARY KEY ( id_fotografia );

ALTER TABLE habitacion ADD CONSTRAINT pk_habitacion PRIMARY KEY ( id_habitacion );

ALTER TABLE reserva ADD CONSTRAINT reserva_pk PRIMARY KEY ( id_reserva );

ALTER TABLE tipo_usuario ADD CONSTRAINT pk_tipo_usuario PRIMARY KEY ( id_tipo_usuario );

ALTER TABLE ubicacion ADD CONSTRAINT pk_ubicacion PRIMARY KEY ( id_ubicacion );

ALTER TABLE usuario ADD CONSTRAINT pk_usuario PRIMARY KEY ( id_usuario );

ALTER TABLE usuario ADD CONSTRAINT correo_electronico UNIQUE ( correo_electronico );

-- CREACION DE FK

ALTER TABLE fotografia
    ADD CONSTRAINT fk_fotografia_hab FOREIGN KEY ( id_habitacion )
        REFERENCES habitacion ( id_habitacion );

ALTER TABLE habitacion
    ADD CONSTRAINT fk_hab_categoria_hab FOREIGN KEY ( id_categoria )
        REFERENCES categoria_hab ( id_categoria );

ALTER TABLE habitacion
    ADD CONSTRAINT fk_hab_estado_hab FOREIGN KEY ( id_estado )
        REFERENCES estado_hab ( id_estado );

ALTER TABLE habitacion
    ADD CONSTRAINT fk_hab_ubicacion_fk FOREIGN KEY ( id_ubicacion )
        REFERENCES ubicacion ( id_ubicacion );

ALTER TABLE reserva
    ADD CONSTRAINT fk_res_estado_reserva FOREIGN KEY ( id_estado )
        REFERENCES estado_reserva ( id_estado );

ALTER TABLE reserva
    ADD CONSTRAINT fk_res_habitacion FOREIGN KEY ( id_habitacion )
        REFERENCES habitacion ( id_habitacion );

ALTER TABLE reserva
    ADD CONSTRAINT fk_res_usuario FOREIGN KEY ( id_usuario )
        REFERENCES usuario ( id_usuario );

ALTER TABLE usuario
    ADD CONSTRAINT fk_usu_tipo_usuario FOREIGN KEY ( id_tipo_usuario )
        REFERENCES tipo_usuario ( id_tipo_usuario );

-- INSERCION DE DATOS EN TABLAS
               
-- Insertar datos en la tabla tipo_usuario
	INSERT INTO tipo_usuario (descripcion) VALUES ('Administrador');
	INSERT INTO tipo_usuario (descripcion) VALUES ('Empleado');
	INSERT INTO tipo_usuario (descripcion) VALUES ('Cliente');

-- Insertar datos en la tabla estado_reserva
	INSERT INTO estado_reserva (desc_est_res) VALUES ('Pendiente');
	INSERT INTO estado_reserva (desc_est_res) VALUES ('Confirmada');
	INSERT INTO estado_reserva (desc_est_res) VALUES ('Cancelada');

-- Insertar datos en la tabla estado_hab
	INSERT INTO estado_hab (desc_est_hab) VALUES ('Disponible');
	INSERT INTO estado_hab (desc_est_hab) VALUES ('Ocupada');
	INSERT INTO estado_hab (desc_est_hab) VALUES ('Mantenimiento');

-- Insertar datos en la tabla ubicacion
	INSERT INTO ubicacion (desc_ubic) VALUES ('Piso 1 - Lobby');
	INSERT INTO ubicacion (desc_ubic) VALUES ('Piso 2 - Zona Tranquila');
	INSERT INTO ubicacion (desc_ubic) VALUES ('Piso 3 - Vista al Mar');
	INSERT INTO ubicacion (desc_ubic) VALUES ('Piso 4 - Piscina');
	INSERT INTO ubicacion (desc_ubic) VALUES ('Piso 5 - Suites Ejecutivas');
	INSERT INTO ubicacion (desc_ubic) VALUES ('Piso 6 - Area Familiar');
	INSERT INTO ubicacion (desc_ubic) VALUES ('Piso 7 - Atico');

-- Insertar datos en la tabla categoria_hab
	INSERT INTO categoria_hab (desc_cat) VALUES ('Turista');
	INSERT INTO categoria_hab (desc_cat) VALUES ('Premium');

-- Inserción de habitaciones en la tabla habitacion (30 Turista, 8 Premium)
	
	-- Habitaciones de la Categoría Turista (Pisos 1 a 3, y Piso 6)
	
	-- Piso 1 - Lobby (6 habitaciones)
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('101', 'Habitacion cerca del lobby, ideal para accesibilidad', 'Cama King, TV, Aire Acondicionado, WiFi', 70000, 1, 1, 1);
	
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('102', 'Habitacion con acceso rapido a recepcion', 'Cama Queen, Escritorio, TV, WiFi', 65000, 1, 1, 1);
	
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('103', 'Habitacion ideal para viajeros de negocios', 'Cama Queen, Escritorio, Minibar, TV, WiFi', 68000, 1, 1, 1);
	
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('104', 'Habitacion cerca del lobby, ideal para accesibilidad', 'Cama King, TV, Aire Acondicionado, WiFi', 70000, 1, 1, 1);
	
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('105', 'Habitacion con acceso rapido a recepcion', 'Cama Queen, Escritorio, TV, WiFi', 65000, 1, 1, 1);
	
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('106', 'Habitacion ideal para viajeros de negocios', 'Cama Queen, Escritorio, Minibar, TV, WiFi', 68000, 1, 1, 1);
	
	-- Piso 2 - Zona Tranquila (8 habitaciones)
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('201', 'Habitacion en zona tranquila, ideal para descanso', 'Cama Queen, TV, Aire Acondicionado, WiFi', 72000, 2, 1, 1);
	
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('202', 'Habitacion en area tranquila, perfecta para parejas', 'Cama Doble, Escritorio, TV, WiFi', 70000, 2, 1, 1);
	
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('203', 'Habitacion silenciosa, ideal para descanso prolongado', 'Cama King, TV, Escritorio, WiFi', 74000, 2, 1, 1);
	
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('204', 'Habitacion con vista interna, ambiente relajante', 'Cama Queen, TV, Aire Acondicionado, WiFi', 70000, 2, 1, 1);
	
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('205', 'Habitacion en area tranquila, ideal para trabajo remoto', 'Cama Doble, Escritorio, TV, WiFi', 72000, 2, 1, 1);
	
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('206', 'Habitacion en zona tranquila, ideal para familias', '2 Camas Dobles, TV, Minibar, WiFi', 75000, 2, 1, 1);
	
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('207', 'Habitacion con balcon privado, zona tranquila', 'Cama King, Balcon, TV, Aire Acondicionado, WiFi', 78000, 2, 1, 1);
	
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('208', 'Habitacion con vista al jardin, zona tranquila', 'Cama Queen, Balcon, TV, WiFi', 75000, 2, 1, 1);
	
	-- Piso 3 - Vista al Mar (10 habitaciones)
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('301', 'Habitacion con vista al mar, balcon privado', 'Cama King, Balcon, TV, Aire Acondicionado, WiFi', 80000, 3, 1, 1);
	
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('302', 'Vista al mar, habitacion con ambiente relajante', 'Cama Queen, Balcon, TV, WiFi', 78000, 3, 1, 1);
	
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('303', 'Habitacion con vistas panoramicas, perfecto para parejas', 'Cama King, TV, Aire Acondicionado, WiFi', 82000, 3, 1, 1);
	
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('304', 'Vista al mar, habitacion con balcon', 'Cama Queen, TV, Balcon, WiFi', 80000, 3, 1, 1);
	
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('305', 'Habitacion con vista al mar, decoracion moderna', 'Cama King, TV, Aire Acondicionado, WiFi', 85000, 3, 1, 1);
	
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('306', 'Habitacion con balcon y vista al mar, ideal para relajarse', 'Cama Queen, Balcon, TV, WiFi', 83000, 3, 1, 1);
	
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('307', 'Habitacion con vistas panoramicas, balcon privado', 'Cama King, Balcon, TV, Aire Acondicionado, WiFi', 85000, 3, 1, 1);
	
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('308', 'Vista al mar, habitacion con area de estar', 'Cama Queen, Sala de estar, TV, WiFi', 90000, 3, 1, 1);
	
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('309', 'Habitacion familiar con vista al mar, balcon privado', '2 Camas Dobles, TV, Aire Acondicionado, WiFi', 95000, 3, 1, 1);
	
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('310', 'Habitacion con balcon privado y vistas al mar', 'Cama King, TV, Aire Acondicionado, WiFi', 100000, 3, 1, 1);
	
	-- Piso 6 - Area Familiar (6 habitaciones)
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('601', 'Habitacion familiar con dos camas dobles', '2 Camas Dobles, TV, Minibar, WiFi', 85000, 6, 1, 1);
	
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('602', 'Habitacion ideal para familias, acceso a zona de juegos', 'Cama Queen, Sofa-cama, TV, WiFi', 80000, 6, 1, 1);
	
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('603', 'Habitacion familiar con area de estar', '2 Camas Dobles, Sala de estar, TV, WiFi', 88000, 6, 1, 1);
	
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('604', 'Habitacion ideal para familias con ninos', 'Cama Queen, Literas, TV, WiFi', 80000, 6, 1, 1);
	
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('605', 'Habitacion familiar con acceso a zona de recreacion', 'Cama Queen, Sofa-cama, TV, WiFi', 85000, 6, 1, 1);
	
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('606', 'Habitacion con dos camas dobles, ideal para familias', '2 Camas Dobles, TV, Minibar, WiFi', 90000, 6, 1, 1);
	
	-- Habitaciones de la Categoría Premium (Pisos 4, 5 y 7)
	
	-- Piso 4 - Piscina (3 habitaciones)
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('401', 'Habitacion premium con acceso directo a la piscina', 'Cama King, Terraza privada, Jacuzzi, TV, WiFi', 150000, 4, 1, 2);
	
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('402', 'Suite con acceso directo a la piscina, ideal para relajarse', 'Cama Queen, Jacuzzi, Terraza Privada, WiFi', 160000, 4, 1, 2);
	
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('403', 'Suite premium con acceso a piscina y terraza privada', 'Cama King, Jacuzzi, Sala de estar, WiFi', 170000, 4, 1, 2);
	
	-- Piso 5 - Suites Ejecutivas (3 habitaciones)
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('501', 'Suite ejecutiva con vista panoramica, perfecta para estancias prolongadas', 'Cama King, Jacuzzi, Minibar, WiFi', 180000, 5, 1, 2);
	
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('502', 'Habitacion de lujo con servicios premium', 'Cama King, Jacuzzi, Sala de estar, WiFi', 200000, 5, 1, 2);
	
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('503', 'Suite ejecutiva con vista a la ciudad, sala de estar', 'Cama Queen, Jacuzzi, Minibar, WiFi', 190000, 5, 1, 2);
	
	-- Piso 7 - Atico (2 habitaciones)
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('701', 'Suite atico con vista 360 grados, terraza privada', 'Cama King, Jacuzzi, Terraza 360, WiFi', 250000, 7, 1, 2);
	
	INSERT INTO habitacion (numero_hab, info_hab, equipamiento_hab, valor_diario_hab, id_ubicacion, id_estado, id_categoria)
	VALUES ('702', 'Suite atico de lujo, ideal para ocasiones especiales', 'Cama King, Terraza privada, Jacuzzi, Sala de estar, WiFi', 270000, 7, 1, 2);

-- Insercion de fotografias de habitaciones
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab101_1.jpg', 1);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab101_2.jpg', 1);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab101_3.jpg', 1);
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab102_2.jpg', 2);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab102_1.jpg', 2);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab102_3.jpg', 2);
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab103_1.jpg', 3);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab103_2.jpg', 3);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab103_3.jpg', 3);
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab104_1.jpg', 4);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab104_2.jpg', 4);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab104_3.jpg', 4);
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab105_1.jpg', 5);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab105_2.jpg', 5);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab105_3.jpg', 5);
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab106_1.jpg', 6);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab106_2.jpg', 6);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab106_3.jpg', 6);
	
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab201_1.jpg', 7);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab201_2.jpg', 7);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab201_3.jpg', 7);
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab202_1.jpg', 8);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab202_2.jpg', 8);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab202_3.jpg', 8);
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab203_1.jpg', 9);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab203_2.jpg', 9);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab203_3.jpg', 9);
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab204_1.jpg', 10);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab204_2.jpg', 10);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab204_3.jpg', 10);
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab205_1.jpg', 11);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab205_2.jpg', 11);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab205_3.jpg', 11);
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab206_1.jpg', 12);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab206_2.jpg', 12);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab206_3.jpg', 12);
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab207_1.jpg', 13);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab207_2.jpg', 13);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab207_3.jpg', 13);
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab208_1.jpg', 14);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab208_2.jpg', 14);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab208_3.jpg', 14);
	
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab301_1.jpg', 15);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab301_2.jpg', 15);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab301_3.jpg', 15);
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab302_1.jpg', 16);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab302_2.jpg', 16);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab302_3.jpg', 16);
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab303_1.jpg', 17);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab303_2.jpg', 17);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab303_3.jpg', 17);
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab304_1.jpg', 18);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab304_2.jpg', 18);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab304_3.jpg', 18);
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab305_1.jpg', 19);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab305_2.jpg', 19);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab305_3.jpg', 19);
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab306_1.jpg', 20);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab306_2.jpg', 20);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab306_3.jpg', 20);
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab307_1.jpg', 21);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab307_2.jpg', 21);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab307_3.jpg', 21);
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab308_1.jpg', 22);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab308_2.jpg', 22);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab308_3.jpg', 22);
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab309_1.jpg', 23);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab309_2.jpg', 23);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab309_3.jpg', 23);
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab310_1.jpg', 24);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab310_2.jpg', 24);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab310_3.jpg', 24);
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab601_1.jpg', 25);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab601_2.jpg', 25);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab601_3.jpg', 25);
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab602_1.jpg', 26);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab602_2.jpg', 26);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab602_3.jpg', 26);
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab603_1.jpg', 27);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab603_2.jpg', 27);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab603_3.jpg', 27);
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab604_1.jpg', 28);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab604_2.jpg', 28);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab604_3.jpg', 28);
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab605_1.jpg', 29);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab605_2.jpg', 29);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab605_3.jpg', 29);
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab606_1.jpg', 30);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab606_2.jpg', 30);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab606_3.jpg', 30);
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab401_1.jpg', 31);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab401_2.jpg', 31);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab401_3.jpg', 31);
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab402_1.jpg', 32);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab402_2.jpg', 32);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab402_3.jpg', 32);
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab403_1.jpg', 33);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab403_2.jpg', 33);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab403_3.jpg', 33);
	
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab501_1.jpg', 34);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab501_2.jpg', 34);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab501_3.jpg', 34);
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab502_1.jpg', 35);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab502_2.jpg', 35);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab502_3.jpg', 35);	
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab503_1.jpg', 36);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab503_2.jpg', 36);	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab503_3.jpg', 36);
	
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab701_1.jpg', 37);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab701_2.jpg', 37);	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab701_3.jpg', 37);
	
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab702_1.jpg', 38);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab702_2.jpg', 38);
	INSERT INTO fotografia (url_fotografia, id_habitacion) VALUES ('/images/hab702_3.jpg', 38);

-- Inserción de Usuarios
	
	-- administrador creado por defecto en sistema
	INSERT INTO usuario (correo_electronico, clave_usuario, nombre_usuario, apellido_usuario, id_tipo_usuario)
	VALUES ('admin@reefreserve.com', 'Admin1234', 'Admin', 'Principal', 1);
	
	-- Administradores
	INSERT INTO usuario (correo_electronico, clave_usuario, nombre_usuario, apellido_usuario, id_tipo_usuario)
	VALUES ('admin1@reefreserve.com', 'Admin123', 'Carlos', 'Gonzalez', 1);
	
	INSERT INTO usuario (correo_electronico, clave_usuario, nombre_usuario, apellido_usuario, id_tipo_usuario)
	VALUES ('admin2@reefreserve.com', 'Admin234', 'Roberto', 'Diaz', 1);
	
	-- Empleados
	INSERT INTO usuario (correo_electronico, clave_usuario, nombre_usuario, apellido_usuario, id_tipo_usuario)
	VALUES ('empleado1@reefreserve.com', 'Emp1234', 'Ana', 'Martinez', 2);
	
	INSERT INTO usuario (correo_electronico, clave_usuario, nombre_usuario, apellido_usuario, id_tipo_usuario)
	VALUES ('empleado2@reefreserve.com', 'Emp2345', 'Marta', 'Perez', 2);
	
	INSERT INTO usuario (correo_electronico, clave_usuario, nombre_usuario, apellido_usuario, id_tipo_usuario)
	VALUES ('empleado3@reefreserve.com', 'Emp3456', 'Mario', 'Lopez', 2);
	
	-- Clientes
	INSERT INTO usuario (correo_electronico, clave_usuario, nombre_usuario, apellido_usuario, id_tipo_usuario)
	VALUES ('cliente1@gmail.com', 'Cliente123', 'Javier', 'Rodriguez', 3);
	
	INSERT INTO usuario (correo_electronico, clave_usuario, nombre_usuario, apellido_usuario, id_tipo_usuario)
	VALUES ('cliente2@gmail.com', 'Cliente234', 'Laura', 'Sanchez', 3);
	
	INSERT INTO usuario (correo_electronico, clave_usuario, nombre_usuario, apellido_usuario, id_tipo_usuario)
	VALUES ('cliente3@gmail.com', 'Cliente345', 'Daniel', 'Ramirez', 3);
	
	INSERT INTO usuario (correo_electronico, clave_usuario, nombre_usuario, apellido_usuario, id_tipo_usuario)
	VALUES ('cliente4@gmail.com', 'Cliente456', 'Sofia', 'Fernandez', 3);
	
	INSERT INTO usuario (correo_electronico, clave_usuario, nombre_usuario, apellido_usuario, id_tipo_usuario)
	VALUES ('cliente5@gmail.com', 'Cliente567', 'Luis', 'Gomez', 3);
	
	INSERT INTO usuario (correo_electronico, clave_usuario, nombre_usuario, apellido_usuario, id_tipo_usuario)
	VALUES ('cliente6@gmail.com', 'Cliente678', 'Fernanda', 'Lopez', 3);
	
	INSERT INTO usuario (correo_electronico, clave_usuario, nombre_usuario, apellido_usuario, id_tipo_usuario)
	VALUES ('cliente7@gmail.com', 'Cliente789', 'Gabriel', 'Silva', 3);
	
	INSERT INTO usuario (correo_electronico, clave_usuario, nombre_usuario, apellido_usuario, id_tipo_usuario)
	VALUES ('cliente8@gmail.com', 'Cliente890', 'Valentina', 'Morales', 3);
	
	INSERT INTO usuario (correo_electronico, clave_usuario, nombre_usuario, apellido_usuario, id_tipo_usuario)
	VALUES ('cliente9@gmail.com', 'Cliente901', 'Diego', 'Castro', 3);
	
	INSERT INTO usuario (correo_electronico, clave_usuario, nombre_usuario, apellido_usuario, id_tipo_usuario)
	VALUES ('cliente10@gmail.com', 'Cliente012', 'Camila', 'Rojas', 3);


-- Inserción de 10 reservas de prueba (solo usuarios clientes pueden reservar)
	
	INSERT INTO reserva (fecha_inicio, fecha_termino, cantidad_dias, abono, costo, id_usuario, id_habitacion, id_estado)
	VALUES (TO_DATE('2024-10-01', 'YYYY-MM-DD'), TO_DATE('2024-10-05', 'YYYY-MM-DD'), 4, 50000, 200000, 7, 15, 2);
	
	INSERT INTO reserva (fecha_inicio, fecha_termino, cantidad_dias, abono, costo, id_usuario, id_habitacion, id_estado)
	VALUES (TO_DATE('2024-10-10', 'YYYY-MM-DD'), TO_DATE('2024-10-13', 'YYYY-MM-DD'), 3, 30000, 90000, 8, 7, 2);
	
	INSERT INTO reserva (fecha_inicio, fecha_termino, cantidad_dias, abono, costo, id_usuario, id_habitacion, id_estado)
	VALUES (TO_DATE('2024-11-05', 'YYYY-MM-DD'), TO_DATE('2024-11-10', 'YYYY-MM-DD'), 5, 75000, 375000, 9, 22, 2);
	
	INSERT INTO reserva (fecha_inicio, fecha_termino, cantidad_dias, abono, costo, id_usuario, id_habitacion, id_estado)
	VALUES (TO_DATE('2024-11-12', 'YYYY-MM-DD'), TO_DATE('2024-11-15', 'YYYY-MM-DD'), 3, 45000, 135000, 10, 31, 2);
	
	INSERT INTO reserva (fecha_inicio, fecha_termino, cantidad_dias, abono, costo, id_usuario, id_habitacion, id_estado)
	VALUES (TO_DATE('2024-12-01', 'YYYY-MM-DD'), TO_DATE('2024-12-03', 'YYYY-MM-DD'), 2, 40000, 80000, 11, 16, 2);
	
	INSERT INTO reserva (fecha_inicio, fecha_termino, cantidad_dias, abono, costo, id_usuario, id_habitacion, id_estado)
	VALUES (TO_DATE('2024-12-10', 'YYYY-MM-DD'), TO_DATE('2024-12-12', 'YYYY-MM-DD'), 2, 30000, 60000, 12, 9, 2);
	
	INSERT INTO reserva (fecha_inicio, fecha_termino, cantidad_dias, abono, costo, id_usuario, id_habitacion, id_estado)
	VALUES (TO_DATE('2025-01-05', 'YYYY-MM-DD'), TO_DATE('2025-01-08', 'YYYY-MM-DD'), 3, 60000, 180000, 13, 19, 2);
	
	INSERT INTO reserva (fecha_inicio, fecha_termino, cantidad_dias, abono, costo, id_usuario, id_habitacion, id_estado)
	VALUES (TO_DATE('2025-01-15', 'YYYY-MM-DD'), TO_DATE('2025-01-18', 'YYYY-MM-DD'), 3, 45000, 135000, 14, 34, 2);
	
	INSERT INTO reserva (fecha_inicio, fecha_termino, cantidad_dias, abono, costo, id_usuario, id_habitacion, id_estado)
	VALUES (TO_DATE('2025-02-01', 'YYYY-MM-DD'), TO_DATE('2025-02-04', 'YYYY-MM-DD'), 3, 55000, 165000, 15, 35, 2);
	
	INSERT INTO reserva (fecha_inicio, fecha_termino, cantidad_dias, abono, costo, id_usuario, id_habitacion, id_estado)
	VALUES (TO_DATE('2025-02-10', 'YYYY-MM-DD'), TO_DATE('2025-02-15', 'YYYY-MM-DD'), 5, 85000, 425000, 16, 37, 2);

-- confirmacion de cambios

COMMIT;